---
# Install and configure MailHog.
- name: Ensure mailhog install directory exists.
  ansible.builtin.file:
    path: "{{ mailhog_install_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Download MailHog and mhsendmail binaries.
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - url: "{{ mailhog_binary_url }}"
      dest: "{{ mailhog_install_dir }}/mailhog"
    - url: "{{ mhsendmail_binary_url }}"
      dest: "{{ mailhog_install_dir }}/mhsendmail"


- name: Create mailhoh enviroment file
  ansible.builtin.template:
    src: mailhog.env.j2
    dest: "{{ mailhog_install_dir }}/env.mailhog"
    owner: root
    group: root
    mode: 0644

- name: Copy mailhog systemd unit file into place (for systemd systems).
  ansible.builtin.template:
    src: mailhog.unit.j2
    dest: /etc/systemd/system/mailhog.service
    owner: root
    group: root
    mode: 0755
  when: "ansible_service_mgr == 'systemd'"

- name: Ensure mailhog is enabled and will start on boot.
  ansible.builtin.service:
    name: mailhog
    state: started
    enabled: true
